<?php
$dalTablerejected_jobfile2 = array();
$dalTablerejected_jobfile2["jobfile_id"] = array("type"=>3,"varname"=>"jobfile_id");
$dalTablerejected_jobfile2["previous_jobfile_id"] = array("type"=>3,"varname"=>"previous_jobfile_id");
$dalTablerejected_jobfile2["file_url"] = array("type"=>201,"varname"=>"file_url");
$dalTablerejected_jobfile2["client_id"] = array("type"=>3,"varname"=>"client_id");
$dalTablerejected_jobfile2["work_id"] = array("type"=>3,"varname"=>"work_id");
$dalTablerejected_jobfile2["job_id"] = array("type"=>3,"varname"=>"job_id");
$dalTablerejected_jobfile2["previous_job_id"] = array("type"=>3,"varname"=>"previous_job_id");
$dalTablerejected_jobfile2["project_id"] = array("type"=>3,"varname"=>"project_id");
$dalTablerejected_jobfile2["folder_name"] = array("type"=>200,"varname"=>"folder_name");
$dalTablerejected_jobfile2["filename"] = array("type"=>201,"varname"=>"filename");
$dalTablerejected_jobfile2["jobfile_type"] = array("type"=>200,"varname"=>"jobfile_type");
$dalTablerejected_jobfile2["jobfile_note"] = array("type"=>201,"varname"=>"jobfile_note");
$dalTablerejected_jobfile2["jobfile_status_id"] = array("type"=>3,"varname"=>"jobfile_status_id");
$dalTablerejected_jobfile2["downloader_id"] = array("type"=>3,"varname"=>"downloader_id");
$dalTablerejected_jobfile2["distributor_id"] = array("type"=>3,"varname"=>"distributor_id");
$dalTablerejected_jobfile2["designer_id"] = array("type"=>3,"varname"=>"designer_id");
$dalTablerejected_jobfile2["qc_id"] = array("type"=>3,"varname"=>"qc_id");
$dalTablerejected_jobfile2["uploader_id"] = array("type"=>3,"varname"=>"uploader_id");
$dalTablerejected_jobfile2["notifier_id"] = array("type"=>3,"varname"=>"notifier_id");
$dalTablerejected_jobfile2["rejector_id"] = array("type"=>3,"varname"=>"rejector_id");
$dalTablerejected_jobfile2["download_date"] = array("type"=>135,"varname"=>"download_date");
$dalTablerejected_jobfile2["distribute_date"] = array("type"=>135,"varname"=>"distribute_date");
$dalTablerejected_jobfile2["start_date"] = array("type"=>135,"varname"=>"start_date");
$dalTablerejected_jobfile2["end_date"] = array("type"=>135,"varname"=>"end_date");
$dalTablerejected_jobfile2["designer_time"] = array("type"=>134,"varname"=>"designer_time");
$dalTablerejected_jobfile2["qcstart_date"] = array("type"=>135,"varname"=>"qcstart_date");
$dalTablerejected_jobfile2["qcend_date"] = array("type"=>135,"varname"=>"qcend_date");
$dalTablerejected_jobfile2["qc_time"] = array("type"=>134,"varname"=>"qc_time");
$dalTablerejected_jobfile2["upload_date"] = array("type"=>135,"varname"=>"upload_date");
$dalTablerejected_jobfile2["notify_date"] = array("type"=>135,"varname"=>"notify_date");
$dalTablerejected_jobfile2["reject_date"] = array("type"=>201,"varname"=>"reject_date");
$dalTablerejected_jobfile2["reject_reason"] = array("type"=>201,"varname"=>"reject_reason");
$dalTablerejected_jobfile2["reject_reason_others"] = array("type"=>201,"varname"=>"reject_reason_others");
$dalTablerejected_jobfile2["screenshots"] = array("type"=>201,"varname"=>"screenshots");
$dalTablerejected_jobfile2["designer2_id"] = array("type"=>3,"varname"=>"designer2_id");
$dalTablerejected_jobfile2["start2_date"] = array("type"=>135,"varname"=>"start2_date");
$dalTablerejected_jobfile2["end2_date"] = array("type"=>135,"varname"=>"end2_date");
$dalTablerejected_jobfile2["designer2_time"] = array("type"=>134,"varname"=>"designer2_time");
	$dalTablerejected_jobfile2["jobfile_id"]["key"]=true;

$dal_info["visionwebapp_at_192_168_2_1__rejected_jobfile2"] = &$dalTablerejected_jobfile2;
?>