<?php

/**
* getLookupMainTableSettings - tests whether the lookup link exists between the tables
*
*  returns array with ProjectSettings class for main table if the link exists in project settings.
*  returns NULL otherwise
*/
function getLookupMainTableSettings($lookupTable, $mainTableShortName, $mainField, $desiredPage = "")
{
	global $lookupTableLinks;
	if(!isset($lookupTableLinks[$lookupTable]))
		return null;
	if(!isset($lookupTableLinks[$lookupTable][$mainTableShortName.".".$mainField]))
		return null;
	$arr = &$lookupTableLinks[$lookupTable][$mainTableShortName.".".$mainField];
	$effectivePage = $desiredPage;
	if(!isset($arr[$effectivePage]))
	{
		$effectivePage = PAGE_EDIT;
		if(!isset($arr[$effectivePage]))
		{
			if($desiredPage == "" && 0 < count($arr))
			{
				$effectivePage = $arr[0];
			}
			else
				return null;
		}
	}
	return new ProjectSettings($arr[$effectivePage]["table"], $effectivePage);
}

/** 
* $lookupTableLinks array stores all lookup links between tables in the project
*/
function InitLookupLinks()
{
	global $lookupTableLinks;

	$lookupTableLinks = array();

	$lookupTableLinks["clients"]["job.client_id"]["edit"] = array("table" => "job", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["job.project_id"]["edit"] = array("table" => "job", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["job.notify_options"]["edit"] = array("table" => "job", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["pdf"]["job.pdf_id"]["edit"] = array("table" => "job", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["job.jobstatus_id"]["edit"] = array("table" => "job", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["job.reviewer_id"]["edit"] = array("table" => "job", "field" => "reviewer_id", "page" => "edit");
	$lookupTableLinks["user"]["job.reviewer_id"]["add"] = array("table" => "job", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["job.reviewer_id"]["search"] = array("table" => "job", "field" => "reviewer_id", "page" => "search");
	$lookupTableLinks["user"]["job.accept_id"]["edit"] = array("table" => "job", "field" => "accept_id", "page" => "edit");
	$lookupTableLinks["user"]["job.accept_id"]["add"] = array("table" => "job", "field" => "accept_id", "page" => "add");
	$lookupTableLinks["user"]["job.accept_id"]["search"] = array("table" => "job", "field" => "accept_id", "page" => "search");
	$lookupTableLinks["user"]["job.downloader_id"]["edit"] = array("table" => "job", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["job.downloader_id"]["add"] = array("table" => "job", "field" => "downloader_id", "page" => "add");
	$lookupTableLinks["user"]["job.downloader_id"]["search"] = array("table" => "job", "field" => "downloader_id", "page" => "search");
	$lookupTableLinks["user"]["job.distributor_id"]["edit"] = array("table" => "job", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["job.uploader_id"]["edit"] = array("table" => "job", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["job.uploader_id"]["add"] = array("table" => "job", "field" => "uploader_id", "page" => "add");
	$lookupTableLinks["user"]["job.uploader_id"]["search"] = array("table" => "job", "field" => "uploader_id", "page" => "search");
	$lookupTableLinks["user"]["job.notifer_id"]["edit"] = array("table" => "job", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["user"]["job.notifer_id"]["add"] = array("table" => "job", "field" => "notifer_id", "page" => "add");
	$lookupTableLinks["user"]["job.notifer_id"]["search"] = array("table" => "job", "field" => "notifer_id", "page" => "search");
	$lookupTableLinks["user"]["job.rejector_id"]["edit"] = array("table" => "job", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["pdf"]["jobfile.job_pdf_name"]["edit"] = array("table" => "jobfile", "field" => "job_pdf_name", "page" => "edit");
	$lookupTableLinks["clients"]["jobfile.client_id"]["edit"] = array("table" => "jobfile", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["jobfile.project_id"]["edit"] = array("table" => "jobfile", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["jobfile.jobfile_status_id"]["edit"] = array("table" => "jobfile", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.downloader_id"]["edit"] = array("table" => "jobfile", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.distributor_id"]["edit"] = array("table" => "jobfile", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.distributor_id"]["add"] = array("table" => "jobfile", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["jobfile.distributor_id"]["search"] = array("table" => "jobfile", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["jobfile.designer_id"]["edit"] = array("table" => "jobfile", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.qc_id"]["edit"] = array("table" => "jobfile", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.qc_id"]["search"] = array("table" => "jobfile", "field" => "qc_id", "page" => "search");
	$lookupTableLinks["user"]["jobfile.uploader_id"]["edit"] = array("table" => "jobfile", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.notifier_id"]["edit"] = array("table" => "jobfile", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.notifier_id"]["add"] = array("table" => "jobfile", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["jobfile.notifier_id"]["search"] = array("table" => "jobfile", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["jobfile.rejector_id"]["edit"] = array("table" => "jobfile", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["jobfile.rejector_id"]["search"] = array("table" => "jobfile", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["jobfile.designer2_id"]["edit"] = array("table" => "jobfile", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["department"]["subdivision.department_id"]["edit"] = array("table" => "subdivision", "field" => "department_id", "page" => "edit");
	$lookupTableLinks["status"]["user.user_status"]["edit"] = array("table" => "user", "field" => "user_status", "page" => "edit");
	$lookupTableLinks["department"]["user.department_id"]["edit"] = array("table" => "user", "field" => "department_id", "page" => "edit");
	$lookupTableLinks["subdivision"]["user.subdiv_id"]["edit"] = array("table" => "user", "field" => "subdiv_id", "page" => "edit");
	$lookupTableLinks["group"]["user.group_id"]["edit"] = array("table" => "user", "field" => "group_id", "page" => "edit");
	$lookupTableLinks["team"]["user.team"]["edit"] = array("table" => "user", "field" => "team", "page" => "edit");
	$lookupTableLinks["ad_uggroups"]["user.ad_group_id"]["edit"] = array("table" => "user", "field" => "ad_group_id", "page" => "edit");
	$lookupTableLinks["designation"]["user.designation"]["edit"] = array("table" => "user", "field" => "designation", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution.designer_id"]["edit"] = array("table" => "File Distribution", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution.designer_id"]["add"] = array("table" => "File Distribution", "field" => "designer_id", "page" => "add");
	$lookupTableLinks["user"]["File_Distribution.designer_id"]["search"] = array("table" => "File Distribution", "field" => "designer_id", "page" => "search");
	$lookupTableLinks["user"]["File_Distribution.qc_id"]["edit"] = array("table" => "File Distribution", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution.qc_id"]["add"] = array("table" => "File Distribution", "field" => "qc_id", "page" => "add");
	$lookupTableLinks["user"]["File_Distribution.qc_id"]["search"] = array("table" => "File Distribution", "field" => "qc_id", "page" => "search");
	$lookupTableLinks["jobstatus"]["File_Distribution.jobfile_status_id"]["edit"] = array("table" => "File Distribution", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution.designer2_id"]["edit"] = array("table" => "File Distribution", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["jobfile_type"]["File_Distribution.jobfile_type"]["edit"] = array("table" => "File Distribution", "field" => "jobfile_type", "page" => "edit");
	$lookupTableLinks["jobfile_type"]["File_Distribution.jobfile_type"]["add"] = array("table" => "File Distribution", "field" => "jobfile_type", "page" => "add");
	$lookupTableLinks["jobfile_type"]["File_Distribution.jobfile_type"]["search"] = array("table" => "File Distribution", "field" => "jobfile_type", "page" => "search");
	$lookupTableLinks["clients"]["Download_Job.client_id"]["edit"] = array("table" => "Download Job", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Download_Job.jobstatus_id"]["edit"] = array("table" => "Download Job", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Pending_Jobs.pdf_id"]["edit"] = array("table" => "Pending Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Pending_Jobs.pdf_id"]["add"] = array("table" => "Pending Jobs", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Pending_Jobs.pdf_id"]["search"] = array("table" => "Pending Jobs", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Pending_Jobs.pdf_location"]["add"] = array("table" => "Pending Jobs", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Pending_Jobs.jobstatus_id"]["edit"] = array("table" => "Pending Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Pending_Jobs.jobstatus_id"]["search"] = array("table" => "Pending Jobs", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Pending_Jobs.client_id"]["edit"] = array("table" => "Pending Jobs", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Pending_Jobs.project_id"]["edit"] = array("table" => "Pending Jobs", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Pending_Jobs.notify_options"]["edit"] = array("table" => "Pending Jobs", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Pending_Jobs.reviewer_id"]["add"] = array("table" => "Pending Jobs", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["clients"]["pdf.client_id"]["edit"] = array("table" => "pdf", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Designer_Worksheet.pdf_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Worksheet.jobstatus_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Worksheet.designer_list"]["search"] = array("table" => "Designer Worksheet", "field" => "designer_list", "page" => "search");
	$lookupTableLinks["clients"]["Designer_Worksheet.client_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Designer_Worksheet.project_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Designer_Worksheet.notify_options"]["edit"] = array("table" => "Designer Worksheet", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Worksheet.reviewer_id"]["add"] = array("table" => "Designer Worksheet", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Worksheet.notifer_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Worksheet.designer_id"]["edit"] = array("table" => "Designer Worksheet", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["clients"]["Designer_Filesheet.client_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Designer_Filesheet.project_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Filesheet.jobfile_status_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.downloader_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.distributor_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.distributor_id"]["add"] = array("table" => "Designer Filesheet", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Filesheet.distributor_id"]["search"] = array("table" => "Designer Filesheet", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Filesheet.designer_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.qc_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.uploader_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.notifier_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.notifier_id"]["add"] = array("table" => "Designer Filesheet", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Filesheet.notifier_id"]["search"] = array("table" => "Designer Filesheet", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Filesheet.rejector_id"]["edit"] = array("table" => "Designer Filesheet", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Filesheet.rejector_id"]["search"] = array("table" => "Designer Filesheet", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["team.team_leader_id"]["edit"] = array("table" => "team", "field" => "team_leader_id", "page" => "edit");
	$lookupTableLinks["user"]["team.team_leader_id"]["add"] = array("table" => "team", "field" => "team_leader_id", "page" => "add");
	$lookupTableLinks["user"]["team.team_leader_id"]["search"] = array("table" => "team", "field" => "team_leader_id", "page" => "search");
	$lookupTableLinks["shifttype"]["team.team_shift"]["edit"] = array("table" => "team", "field" => "team_shift", "page" => "edit");
	$lookupTableLinks["pdf"]["QC_Worksheet.pdf_id"]["edit"] = array("table" => "QC Worksheet", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["QC_Worksheet.jobstatus_id"]["edit"] = array("table" => "QC Worksheet", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet.designer_list"]["search"] = array("table" => "QC Worksheet", "field" => "designer_list", "page" => "search");
	$lookupTableLinks["clients"]["QC_Worksheet.client_id"]["edit"] = array("table" => "QC Worksheet", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["QC_Worksheet.project_id"]["edit"] = array("table" => "QC Worksheet", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["QC_Worksheet.notify_options"]["edit"] = array("table" => "QC Worksheet", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet.reviewer_id"]["add"] = array("table" => "QC Worksheet", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Worksheet.notifer_id"]["edit"] = array("table" => "QC Worksheet", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["clients"]["QC_Filesheet.client_id"]["edit"] = array("table" => "QC Filesheet", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["QC_Filesheet.project_id"]["edit"] = array("table" => "QC Filesheet", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["QC_Filesheet.jobfile_status_id"]["edit"] = array("table" => "QC Filesheet", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.downloader_id"]["edit"] = array("table" => "QC Filesheet", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.distributor_id"]["edit"] = array("table" => "QC Filesheet", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.distributor_id"]["add"] = array("table" => "QC Filesheet", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Filesheet.distributor_id"]["search"] = array("table" => "QC Filesheet", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet.designer_id"]["edit"] = array("table" => "QC Filesheet", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.qc_id"]["edit"] = array("table" => "QC Filesheet", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.uploader_id"]["edit"] = array("table" => "QC Filesheet", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.notifier_id"]["edit"] = array("table" => "QC Filesheet", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.notifier_id"]["add"] = array("table" => "QC Filesheet", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Filesheet.notifier_id"]["search"] = array("table" => "QC Filesheet", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet.rejector_id"]["edit"] = array("table" => "QC Filesheet", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet.rejector_id"]["search"] = array("table" => "QC Filesheet", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet.designer2_id"]["edit"] = array("table" => "QC Filesheet", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["pdf"]["All_Jobs.pdf_id"]["edit"] = array("table" => "All Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["All_Jobs.jobstatus_id"]["edit"] = array("table" => "All Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["clients"]["All_Jobs.client_id"]["edit"] = array("table" => "All Jobs", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["All_Jobs.project_id"]["edit"] = array("table" => "All Jobs", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["All_Jobs.notify_options"]["edit"] = array("table" => "All Jobs", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["All_Jobs.reviewer_id"]["add"] = array("table" => "All Jobs", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["All_Jobs.notifer_id"]["edit"] = array("table" => "All Jobs", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Daily_Job_Report__Accepted_.pdf_id"]["search"] = array("table" => "Daily Job Report (Accepted)", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["status"]["Users.user_status"]["edit"] = array("table" => "Users", "field" => "user_status", "page" => "edit");
	$lookupTableLinks["department"]["Users.department_id"]["edit"] = array("table" => "Users", "field" => "department_id", "page" => "edit");
	$lookupTableLinks["subdivision"]["Users.subdiv_id"]["edit"] = array("table" => "Users", "field" => "subdiv_id", "page" => "edit");
	$lookupTableLinks["group"]["Users.group_id"]["edit"] = array("table" => "Users", "field" => "group_id", "page" => "edit");
	$lookupTableLinks["team"]["Users.team"]["edit"] = array("table" => "Users", "field" => "team", "page" => "edit");
	$lookupTableLinks["ad_uggroups"]["Users.ad_group_id"]["edit"] = array("table" => "Users", "field" => "ad_group_id", "page" => "edit");
	$lookupTableLinks["designation"]["Users.designation"]["edit"] = array("table" => "Users", "field" => "designation", "page" => "edit");
	$lookupTableLinks["pdf"]["Designer_Level_2.pdf_id"]["edit"] = array("table" => "Designer Level 2", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Level_2.jobstatus_id"]["edit"] = array("table" => "Designer Level 2", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2.designer_list"]["search"] = array("table" => "Designer Level 2", "field" => "designer_list", "page" => "search");
	$lookupTableLinks["clients"]["Designer_Level_2.client_id"]["edit"] = array("table" => "Designer Level 2", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Designer_Level_2.project_id"]["edit"] = array("table" => "Designer Level 2", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Designer_Level_2.notify_options"]["edit"] = array("table" => "Designer Level 2", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2.reviewer_id"]["add"] = array("table" => "Designer Level 2", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level_2.notifer_id"]["edit"] = array("table" => "Designer Level 2", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2.designer_id"]["edit"] = array("table" => "Designer Level 2", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2.designer2_id"]["edit"] = array("table" => "Designer Level 2", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["clients"]["Designer_Level2_Filesheet.client_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Designer_Level2_Filesheet.project_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Level2_Filesheet.jobfile_status_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.downloader_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.distributor_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.distributor_id"]["add"] = array("table" => "Designer Level2 Filesheet", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.distributor_id"]["search"] = array("table" => "Designer Level2 Filesheet", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.designer_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.qc_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.uploader_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.notifier_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.notifier_id"]["add"] = array("table" => "Designer Level2 Filesheet", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.notifier_id"]["search"] = array("table" => "Designer Level2 Filesheet", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.rejector_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.rejector_id"]["search"] = array("table" => "Designer Level2 Filesheet", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet.designer2_id"]["edit"] = array("table" => "Designer Level2 Filesheet", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Urgent_Jobs.pdf_id"]["edit"] = array("table" => "Urgent Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Urgent_Jobs.pdf_id"]["add"] = array("table" => "Urgent Jobs", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Urgent_Jobs.pdf_id"]["search"] = array("table" => "Urgent Jobs", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Urgent_Jobs.pdf_location"]["add"] = array("table" => "Urgent Jobs", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Urgent_Jobs.jobstatus_id"]["edit"] = array("table" => "Urgent Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Urgent_Jobs.jobstatus_id"]["search"] = array("table" => "Urgent Jobs", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Urgent_Jobs.client_id"]["edit"] = array("table" => "Urgent Jobs", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Urgent_Jobs.project_id"]["edit"] = array("table" => "Urgent Jobs", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Urgent_Jobs.notify_options"]["edit"] = array("table" => "Urgent Jobs", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Urgent_Jobs.reviewer_id"]["add"] = array("table" => "Urgent Jobs", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Deadline_Missed.pdf_id"]["edit"] = array("table" => "Deadline Missed", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Deadline_Missed.pdf_id"]["add"] = array("table" => "Deadline Missed", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Deadline_Missed.pdf_id"]["search"] = array("table" => "Deadline Missed", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Deadline_Missed.pdf_location"]["add"] = array("table" => "Deadline Missed", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Deadline_Missed.jobstatus_id"]["edit"] = array("table" => "Deadline Missed", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Deadline_Missed.jobstatus_id"]["search"] = array("table" => "Deadline Missed", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Deadline_Missed.client_id"]["edit"] = array("table" => "Deadline Missed", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Deadline_Missed.project_id"]["edit"] = array("table" => "Deadline Missed", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Deadline_Missed.notify_options"]["edit"] = array("table" => "Deadline Missed", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Deadline_Missed.reviewer_id"]["add"] = array("table" => "Deadline Missed", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_to_Accept.pdf_id"]["edit"] = array("table" => "Need to Accept", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Need_to_Accept.pdf_id"]["add"] = array("table" => "Need to Accept", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_to_Accept.pdf_id"]["search"] = array("table" => "Need to Accept", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Need_to_Accept.pdf_location"]["add"] = array("table" => "Need to Accept", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Need_to_Accept.jobstatus_id"]["edit"] = array("table" => "Need to Accept", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Need_to_Accept.jobstatus_id"]["search"] = array("table" => "Need to Accept", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Need_to_Accept.client_id"]["edit"] = array("table" => "Need to Accept", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Need_to_Accept.project_id"]["edit"] = array("table" => "Need to Accept", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Need_to_Accept.notify_options"]["edit"] = array("table" => "Need to Accept", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Need_to_Accept.reviewer_id"]["add"] = array("table" => "Need to Accept", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Notify.pdf_id"]["edit"] = array("table" => "Need Notify", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Need_Notify.pdf_id"]["add"] = array("table" => "Need Notify", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Notify.pdf_id"]["search"] = array("table" => "Need Notify", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Need_Notify.pdf_location"]["add"] = array("table" => "Need Notify", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Need_Notify.jobstatus_id"]["edit"] = array("table" => "Need Notify", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Need_Notify.jobstatus_id"]["search"] = array("table" => "Need Notify", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Need_Notify.client_id"]["edit"] = array("table" => "Need Notify", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Need_Notify.project_id"]["edit"] = array("table" => "Need Notify", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Need_Notify.notify_options"]["edit"] = array("table" => "Need Notify", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Need_Notify.reviewer_id"]["add"] = array("table" => "Need Notify", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Download.pdf_id"]["edit"] = array("table" => "Need Download", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Need_Download.pdf_id"]["add"] = array("table" => "Need Download", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Download.pdf_id"]["search"] = array("table" => "Need Download", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Need_Download.pdf_location"]["add"] = array("table" => "Need Download", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Need_Download.jobstatus_id"]["edit"] = array("table" => "Need Download", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Need_Download.jobstatus_id"]["search"] = array("table" => "Need Download", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Need_Download.client_id"]["edit"] = array("table" => "Need Download", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Need_Download.project_id"]["edit"] = array("table" => "Need Download", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Need_Download.notify_options"]["edit"] = array("table" => "Need Download", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Need_Download.reviewer_id"]["add"] = array("table" => "Need Download", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_QC.pdf_id"]["edit"] = array("table" => "Need QC", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Need_QC.pdf_id"]["add"] = array("table" => "Need QC", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_QC.pdf_id"]["search"] = array("table" => "Need QC", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Need_QC.pdf_location"]["add"] = array("table" => "Need QC", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Need_QC.jobstatus_id"]["edit"] = array("table" => "Need QC", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Need_QC.jobstatus_id"]["search"] = array("table" => "Need QC", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Need_QC.client_id"]["edit"] = array("table" => "Need QC", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Need_QC.project_id"]["edit"] = array("table" => "Need QC", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Need_QC.notify_options"]["edit"] = array("table" => "Need QC", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Need_QC.reviewer_id"]["add"] = array("table" => "Need QC", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Upload.pdf_id"]["edit"] = array("table" => "Need Upload", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Need_Upload.pdf_id"]["add"] = array("table" => "Need Upload", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Need_Upload.pdf_id"]["search"] = array("table" => "Need Upload", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Need_Upload.pdf_location"]["add"] = array("table" => "Need Upload", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Need_Upload.jobstatus_id"]["edit"] = array("table" => "Need Upload", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Need_Upload.jobstatus_id"]["search"] = array("table" => "Need Upload", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Need_Upload.client_id"]["edit"] = array("table" => "Need Upload", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Need_Upload.project_id"]["edit"] = array("table" => "Need Upload", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Need_Upload.notify_options"]["edit"] = array("table" => "Need Upload", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Need_Upload.reviewer_id"]["add"] = array("table" => "Need Upload", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Pending_14704.pdf_id"]["edit"] = array("table" => "Pending 14704", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Pending_14704.pdf_id"]["add"] = array("table" => "Pending 14704", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Pending_14704.pdf_id"]["search"] = array("table" => "Pending 14704", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Pending_14704.pdf_location"]["add"] = array("table" => "Pending 14704", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Pending_14704.jobstatus_id"]["edit"] = array("table" => "Pending 14704", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Pending_14704.jobstatus_id"]["search"] = array("table" => "Pending 14704", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Pending_14704.client_id"]["edit"] = array("table" => "Pending 14704", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Pending_14704.project_id"]["edit"] = array("table" => "Pending 14704", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Pending_14704.notify_options"]["edit"] = array("table" => "Pending 14704", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Pending_14704.reviewer_id"]["add"] = array("table" => "Pending 14704", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Daily_Job_Report__Notified_.pdf_id"]["search"] = array("table" => "Daily Job Report (Notified)", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_QC.pdf_id"]["edit"] = array("table" => "14704 Need QC", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Need_QC.pdf_id"]["add"] = array("table" => "14704 Need QC", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_QC.pdf_id"]["search"] = array("table" => "14704 Need QC", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_QC.pdf_location"]["add"] = array("table" => "14704 Need QC", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Need_QC.jobstatus_id"]["edit"] = array("table" => "14704 Need QC", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Need_QC.jobstatus_id"]["search"] = array("table" => "14704 Need QC", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Need_QC.client_id"]["edit"] = array("table" => "14704 Need QC", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Need_QC.project_id"]["edit"] = array("table" => "14704 Need QC", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Need_QC.notify_options"]["edit"] = array("table" => "14704 Need QC", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Need_QC.reviewer_id"]["add"] = array("table" => "14704 Need QC", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Upload.pdf_id"]["edit"] = array("table" => "14704 Need Upload", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Need_Upload.pdf_id"]["add"] = array("table" => "14704 Need Upload", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Upload.pdf_id"]["search"] = array("table" => "14704 Need Upload", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_Upload.pdf_location"]["add"] = array("table" => "14704 Need Upload", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Need_Upload.jobstatus_id"]["edit"] = array("table" => "14704 Need Upload", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Need_Upload.jobstatus_id"]["search"] = array("table" => "14704 Need Upload", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Need_Upload.client_id"]["edit"] = array("table" => "14704 Need Upload", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Need_Upload.project_id"]["edit"] = array("table" => "14704 Need Upload", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Need_Upload.notify_options"]["edit"] = array("table" => "14704 Need Upload", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Need_Upload.reviewer_id"]["add"] = array("table" => "14704 Need Upload", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Download.pdf_id"]["edit"] = array("table" => "14704 Need Download", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Need_Download.pdf_id"]["add"] = array("table" => "14704 Need Download", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Download.pdf_id"]["search"] = array("table" => "14704 Need Download", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_Download.pdf_location"]["add"] = array("table" => "14704 Need Download", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Need_Download.jobstatus_id"]["edit"] = array("table" => "14704 Need Download", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Need_Download.jobstatus_id"]["search"] = array("table" => "14704 Need Download", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Need_Download.client_id"]["edit"] = array("table" => "14704 Need Download", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Need_Download.project_id"]["edit"] = array("table" => "14704 Need Download", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Need_Download.notify_options"]["edit"] = array("table" => "14704 Need Download", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Need_Download.reviewer_id"]["add"] = array("table" => "14704 Need Download", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Notify.pdf_id"]["edit"] = array("table" => "14704 Need Notify", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Need_Notify.pdf_id"]["add"] = array("table" => "14704 Need Notify", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Notify.pdf_id"]["search"] = array("table" => "14704 Need Notify", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_Notify.pdf_location"]["add"] = array("table" => "14704 Need Notify", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Need_Notify.jobstatus_id"]["edit"] = array("table" => "14704 Need Notify", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Need_Notify.jobstatus_id"]["search"] = array("table" => "14704 Need Notify", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Need_Notify.client_id"]["edit"] = array("table" => "14704 Need Notify", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Need_Notify.project_id"]["edit"] = array("table" => "14704 Need Notify", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Need_Notify.notify_options"]["edit"] = array("table" => "14704 Need Notify", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Need_Notify.reviewer_id"]["add"] = array("table" => "14704 Need Notify", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Accept.pdf_id"]["edit"] = array("table" => "14704 Need Accept", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Need_Accept.pdf_id"]["add"] = array("table" => "14704 Need Accept", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Need_Accept.pdf_id"]["search"] = array("table" => "14704 Need Accept", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Need_Accept.pdf_location"]["add"] = array("table" => "14704 Need Accept", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Need_Accept.jobstatus_id"]["edit"] = array("table" => "14704 Need Accept", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Need_Accept.jobstatus_id"]["search"] = array("table" => "14704 Need Accept", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Need_Accept.client_id"]["edit"] = array("table" => "14704 Need Accept", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Need_Accept.project_id"]["edit"] = array("table" => "14704 Need Accept", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Need_Accept.notify_options"]["edit"] = array("table" => "14704 Need Accept", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Need_Accept.reviewer_id"]["add"] = array("table" => "14704 Need Accept", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Deadline_Missed.pdf_id"]["edit"] = array("table" => "14704 Deadline Missed", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Deadline_Missed.pdf_id"]["add"] = array("table" => "14704 Deadline Missed", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Deadline_Missed.pdf_id"]["search"] = array("table" => "14704 Deadline Missed", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Deadline_Missed.pdf_location"]["add"] = array("table" => "14704 Deadline Missed", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Deadline_Missed.jobstatus_id"]["edit"] = array("table" => "14704 Deadline Missed", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Deadline_Missed.jobstatus_id"]["search"] = array("table" => "14704 Deadline Missed", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Deadline_Missed.client_id"]["edit"] = array("table" => "14704 Deadline Missed", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Deadline_Missed.project_id"]["edit"] = array("table" => "14704 Deadline Missed", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Deadline_Missed.notify_options"]["edit"] = array("table" => "14704 Deadline Missed", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Deadline_Missed.reviewer_id"]["add"] = array("table" => "14704 Deadline Missed", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Urgent_Jobs.pdf_id"]["edit"] = array("table" => "14704 Urgent Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Urgent_Jobs.pdf_id"]["add"] = array("table" => "14704 Urgent Jobs", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["14704_Urgent_Jobs.pdf_id"]["search"] = array("table" => "14704 Urgent Jobs", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Urgent_Jobs.pdf_location"]["add"] = array("table" => "14704 Urgent Jobs", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["14704_Urgent_Jobs.jobstatus_id"]["edit"] = array("table" => "14704 Urgent Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["14704_Urgent_Jobs.jobstatus_id"]["search"] = array("table" => "14704 Urgent Jobs", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["14704_Urgent_Jobs.client_id"]["edit"] = array("table" => "14704 Urgent Jobs", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["14704_Urgent_Jobs.project_id"]["edit"] = array("table" => "14704 Urgent Jobs", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["14704_Urgent_Jobs.notify_options"]["edit"] = array("table" => "14704 Urgent Jobs", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["14704_Urgent_Jobs.reviewer_id"]["add"] = array("table" => "14704 Urgent Jobs", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["File_Reject.designer_id"]["edit"] = array("table" => "File Reject", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Reject.designer_id"]["add"] = array("table" => "File Reject", "field" => "designer_id", "page" => "add");
	$lookupTableLinks["user"]["File_Reject.designer_id"]["search"] = array("table" => "File Reject", "field" => "designer_id", "page" => "search");
	$lookupTableLinks["user"]["File_Reject.qc_id"]["edit"] = array("table" => "File Reject", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Reject.qc_id"]["add"] = array("table" => "File Reject", "field" => "qc_id", "page" => "add");
	$lookupTableLinks["user"]["File_Reject.qc_id"]["search"] = array("table" => "File Reject", "field" => "qc_id", "page" => "search");
	$lookupTableLinks["jobstatus"]["File_Reject.jobfile_status_id"]["edit"] = array("table" => "File Reject", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Reject.designer2_id"]["edit"] = array("table" => "File Reject", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["user"]["14704_Daily_Report_Full.designer2_id"]["search"] = array("table" => "14704 Daily Report Full", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Daily_Report_Full.project_id"]["search"] = array("table" => "14704 Daily Report Full", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["14704_Daily_Report_Full.team"]["search"] = array("table" => "14704 Daily Report Full", "field" => "team", "page" => "search");
	$lookupTableLinks["jobfile"]["rejected_jobfile.jobfile_id"]["add"] = array("table" => "rejected_jobfile", "field" => "jobfile_id", "page" => "add");
	$lookupTableLinks["jobstatus"]["rejected_jobfile.rejected_jobfile_status_id"]["edit"] = array("table" => "rejected_jobfile", "field" => "rejected_jobfile_status_id", "page" => "edit");
	$lookupTableLinks["pdf"]["rejected_jobfile.pdf_id"]["edit"] = array("table" => "rejected_jobfile", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.rejector_id"]["edit"] = array("table" => "rejected_jobfile", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.original_designer"]["edit"] = array("table" => "rejected_jobfile", "field" => "original_designer", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.original_designer"]["add"] = array("table" => "rejected_jobfile", "field" => "original_designer", "page" => "add");
	$lookupTableLinks["user"]["rejected_jobfile.original_designer"]["search"] = array("table" => "rejected_jobfile", "field" => "original_designer", "page" => "search");
	$lookupTableLinks["user"]["rejected_jobfile.original_designer2"]["edit"] = array("table" => "rejected_jobfile", "field" => "original_designer2", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.original_qc"]["edit"] = array("table" => "rejected_jobfile", "field" => "original_qc", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.cr_designer_id"]["edit"] = array("table" => "rejected_jobfile", "field" => "cr_designer_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile.cr_designer_id"]["add"] = array("table" => "rejected_jobfile", "field" => "cr_designer_id", "page" => "add");
	$lookupTableLinks["user"]["rejected_jobfile.cr_designer_id"]["search"] = array("table" => "rejected_jobfile", "field" => "cr_designer_id", "page" => "search");
	$lookupTableLinks["user"]["rejected_jobfile.cr_qc_id"]["edit"] = array("table" => "rejected_jobfile", "field" => "cr_qc_id", "page" => "edit");
	$lookupTableLinks["type_of_errors"]["rejected_jobfile.type_of_error"]["edit"] = array("table" => "rejected_jobfile", "field" => "type_of_error", "page" => "edit");
	$lookupTableLinks["user"]["14704_Designer_Report.designer2_id"]["edit"] = array("table" => "14704 Designer Report", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["pdf"]["14704_Designer_Report.project_id"]["edit"] = array("table" => "14704 Designer Report", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["team"]["14704_Designer_Report.team"]["edit"] = array("table" => "14704 Designer Report", "field" => "team", "page" => "edit");
	$lookupTableLinks["department"]["Team_Report.department_id"]["search"] = array("table" => "Team Report", "field" => "department_id", "page" => "search");
	$lookupTableLinks["subdivision"]["Team_Report.subdiv_id"]["search"] = array("table" => "Team Report", "field" => "subdiv_id", "page" => "search");
	$lookupTableLinks["group"]["Team_Report.group_id"]["search"] = array("table" => "Team Report", "field" => "group_id", "page" => "search");
	$lookupTableLinks["team"]["Team_Report.team"]["search"] = array("table" => "Team Report", "field" => "team", "page" => "search");
	$lookupTableLinks["jobfile"]["Correction_Files.jobfile_id"]["add"] = array("table" => "Correction Files", "field" => "jobfile_id", "page" => "add");
	$lookupTableLinks["jobstatus"]["Correction_Files.rejected_jobfile_status_id"]["edit"] = array("table" => "Correction Files", "field" => "rejected_jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.rejector_id"]["edit"] = array("table" => "Correction Files", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.original_designer"]["edit"] = array("table" => "Correction Files", "field" => "original_designer", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.original_designer"]["add"] = array("table" => "Correction Files", "field" => "original_designer", "page" => "add");
	$lookupTableLinks["user"]["Correction_Files.original_designer"]["search"] = array("table" => "Correction Files", "field" => "original_designer", "page" => "search");
	$lookupTableLinks["user"]["Correction_Files.original_designer2"]["edit"] = array("table" => "Correction Files", "field" => "original_designer2", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.original_qc"]["edit"] = array("table" => "Correction Files", "field" => "original_qc", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.cr_designer_id"]["edit"] = array("table" => "Correction Files", "field" => "cr_designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Correction_Files.cr_designer_id"]["add"] = array("table" => "Correction Files", "field" => "cr_designer_id", "page" => "add");
	$lookupTableLinks["user"]["Correction_Files.cr_designer_id"]["search"] = array("table" => "Correction Files", "field" => "cr_designer_id", "page" => "search");
	$lookupTableLinks["user"]["Correction_Files.cr_qc_id"]["edit"] = array("table" => "Correction Files", "field" => "cr_qc_id", "page" => "edit");
	$lookupTableLinks["type_of_errors"]["Correction_Files.type_of_error"]["edit"] = array("table" => "Correction Files", "field" => "type_of_error", "page" => "edit");
	$lookupTableLinks["clients"]["Client_Instruction.client_id"]["edit"] = array("table" => "Client Instruction", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["user"]["14704_Monthly_Report_Full.designer2_id"]["search"] = array("table" => "14704 Monthly Report Full", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Monthly_Report_Full.project_id"]["search"] = array("table" => "14704 Monthly Report Full", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["14704_Monthly_Report_Full.team"]["search"] = array("table" => "14704 Monthly Report Full", "field" => "team", "page" => "search");
	$lookupTableLinks["team"]["14704_Daily_Report_Designers.team"]["search"] = array("table" => "14704 Daily Report Designers", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["14704_Daily_Report_Designers.designer2_id"]["search"] = array("table" => "14704 Daily Report Designers", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Daily_Report_Designers.project_id"]["search"] = array("table" => "14704 Daily Report Designers", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["14704_Daily_Report__Team.team"]["search"] = array("table" => "14704 Daily Report  Team", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["14704_Daily_Report__Team.designer2_id"]["search"] = array("table" => "14704 Daily Report  Team", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Daily_Report__Team.project_id"]["search"] = array("table" => "14704 Daily Report  Team", "field" => "project_id", "page" => "search");
	$lookupTableLinks["pdf"]["Delected_Jobs.pdf_id"]["edit"] = array("table" => "Delected Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Delected_Jobs.jobstatus_id"]["edit"] = array("table" => "Delected Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["team"]["14704_Monthly_Report_Team.team"]["search"] = array("table" => "14704 Monthly Report Team", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["14704_Monthly_Report_Team.designer2_id"]["search"] = array("table" => "14704 Monthly Report Team", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Monthly_Report_Team.project_id"]["search"] = array("table" => "14704 Monthly Report Team", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["Daily_Report_Designers.team_id"]["search"] = array("table" => "Daily Report Designers", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Daily_Report_Designers.designer_name"]["search"] = array("table" => "Daily Report Designers", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["Daily_Report_Team.team_id"]["search"] = array("table" => "Daily Report Team", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Daily_Report_Full.designer2_id"]["search"] = array("table" => "Daily Report Full", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["Daily_Report_Full.project_id"]["search"] = array("table" => "Daily Report Full", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["Daily_Report_Full.team"]["search"] = array("table" => "Daily Report Full", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["Monthly_Report_Full.designer2_id"]["search"] = array("table" => "Monthly Report Full", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["Monthly_Report_Full.project_id"]["search"] = array("table" => "Monthly Report Full", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["Monthly_Report_Full.team"]["search"] = array("table" => "Monthly Report Full", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["Capacity___Night_Shift.designer2_id"]["search"] = array("table" => "Capacity - Night Shift", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["team"]["Capacity___Night_Shift.team"]["search"] = array("table" => "Capacity - Night Shift", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["Capacity___Morning_Shift.designer2_id"]["search"] = array("table" => "Capacity - Morning Shift", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["team"]["Capacity___Morning_Shift.team"]["search"] = array("table" => "Capacity - Morning Shift", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["Capacity___Evening_Shift.designer2_id"]["search"] = array("table" => "Capacity - Evening Shift", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["team"]["Capacity___Evening_Shift.team"]["search"] = array("table" => "Capacity - Evening Shift", "field" => "team", "page" => "search");
	$lookupTableLinks["pdf"]["Pending_18442.pdf_id"]["edit"] = array("table" => "Pending 18442", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Pending_18442.pdf_id"]["add"] = array("table" => "Pending 18442", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["Pending_18442.pdf_id"]["search"] = array("table" => "Pending 18442", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Pending_18442.pdf_location"]["add"] = array("table" => "Pending 18442", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["Pending_18442.jobstatus_id"]["edit"] = array("table" => "Pending 18442", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Pending_18442.jobstatus_id"]["search"] = array("table" => "Pending 18442", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["Pending_18442.client_id"]["edit"] = array("table" => "Pending 18442", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Pending_18442.project_id"]["edit"] = array("table" => "Pending 18442", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["Pending_18442.notify_options"]["edit"] = array("table" => "Pending 18442", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["Pending_18442.reviewer_id"]["add"] = array("table" => "Pending 18442", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Deadline_Missed.pdf_id"]["edit"] = array("table" => "18442 Deadline Missed", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Deadline_Missed.pdf_id"]["add"] = array("table" => "18442 Deadline Missed", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Deadline_Missed.pdf_id"]["search"] = array("table" => "18442 Deadline Missed", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Deadline_Missed.pdf_location"]["add"] = array("table" => "18442 Deadline Missed", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Deadline_Missed.jobstatus_id"]["edit"] = array("table" => "18442 Deadline Missed", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Deadline_Missed.jobstatus_id"]["search"] = array("table" => "18442 Deadline Missed", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Deadline_Missed.client_id"]["edit"] = array("table" => "18442 Deadline Missed", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Deadline_Missed.project_id"]["edit"] = array("table" => "18442 Deadline Missed", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Deadline_Missed.notify_options"]["edit"] = array("table" => "18442 Deadline Missed", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Deadline_Missed.reviewer_id"]["add"] = array("table" => "18442 Deadline Missed", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Urgent_Jobs.pdf_id"]["edit"] = array("table" => "18442 Urgent Jobs", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Urgent_Jobs.pdf_id"]["add"] = array("table" => "18442 Urgent Jobs", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Urgent_Jobs.pdf_id"]["search"] = array("table" => "18442 Urgent Jobs", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Urgent_Jobs.pdf_location"]["add"] = array("table" => "18442 Urgent Jobs", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Urgent_Jobs.jobstatus_id"]["edit"] = array("table" => "18442 Urgent Jobs", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Urgent_Jobs.jobstatus_id"]["search"] = array("table" => "18442 Urgent Jobs", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Urgent_Jobs.client_id"]["edit"] = array("table" => "18442 Urgent Jobs", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Urgent_Jobs.project_id"]["edit"] = array("table" => "18442 Urgent Jobs", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Urgent_Jobs.notify_options"]["edit"] = array("table" => "18442 Urgent Jobs", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Urgent_Jobs.reviewer_id"]["add"] = array("table" => "18442 Urgent Jobs", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Notify.pdf_id"]["edit"] = array("table" => "18442 Need Notify", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Need_Notify.pdf_id"]["add"] = array("table" => "18442 Need Notify", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Notify.pdf_id"]["search"] = array("table" => "18442 Need Notify", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Need_Notify.pdf_location"]["add"] = array("table" => "18442 Need Notify", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Need_Notify.jobstatus_id"]["edit"] = array("table" => "18442 Need Notify", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Need_Notify.jobstatus_id"]["search"] = array("table" => "18442 Need Notify", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Need_Notify.client_id"]["edit"] = array("table" => "18442 Need Notify", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Need_Notify.project_id"]["edit"] = array("table" => "18442 Need Notify", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Need_Notify.notify_options"]["edit"] = array("table" => "18442 Need Notify", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Need_Notify.reviewer_id"]["add"] = array("table" => "18442 Need Notify", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Upload.pdf_id"]["edit"] = array("table" => "18442 Need Upload", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Need_Upload.pdf_id"]["add"] = array("table" => "18442 Need Upload", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Upload.pdf_id"]["search"] = array("table" => "18442 Need Upload", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Need_Upload.pdf_location"]["add"] = array("table" => "18442 Need Upload", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Need_Upload.jobstatus_id"]["edit"] = array("table" => "18442 Need Upload", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Need_Upload.jobstatus_id"]["search"] = array("table" => "18442 Need Upload", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Need_Upload.client_id"]["edit"] = array("table" => "18442 Need Upload", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Need_Upload.project_id"]["edit"] = array("table" => "18442 Need Upload", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Need_Upload.notify_options"]["edit"] = array("table" => "18442 Need Upload", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Need_Upload.reviewer_id"]["add"] = array("table" => "18442 Need Upload", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_QC.pdf_id"]["edit"] = array("table" => "18442 Need QC", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Need_QC.pdf_id"]["add"] = array("table" => "18442 Need QC", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_QC.pdf_id"]["search"] = array("table" => "18442 Need QC", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Need_QC.pdf_location"]["add"] = array("table" => "18442 Need QC", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Need_QC.jobstatus_id"]["edit"] = array("table" => "18442 Need QC", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Need_QC.jobstatus_id"]["search"] = array("table" => "18442 Need QC", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Need_QC.client_id"]["edit"] = array("table" => "18442 Need QC", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Need_QC.project_id"]["edit"] = array("table" => "18442 Need QC", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Need_QC.notify_options"]["edit"] = array("table" => "18442 Need QC", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Need_QC.reviewer_id"]["add"] = array("table" => "18442 Need QC", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Download.pdf_id"]["edit"] = array("table" => "18442 Need Download", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Need_Download.pdf_id"]["add"] = array("table" => "18442 Need Download", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Download.pdf_id"]["search"] = array("table" => "18442 Need Download", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Need_Download.pdf_location"]["add"] = array("table" => "18442 Need Download", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Need_Download.jobstatus_id"]["edit"] = array("table" => "18442 Need Download", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Need_Download.jobstatus_id"]["search"] = array("table" => "18442 Need Download", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Need_Download.client_id"]["edit"] = array("table" => "18442 Need Download", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Need_Download.project_id"]["edit"] = array("table" => "18442 Need Download", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Need_Download.notify_options"]["edit"] = array("table" => "18442 Need Download", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Need_Download.reviewer_id"]["add"] = array("table" => "18442 Need Download", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Accept.pdf_id"]["edit"] = array("table" => "18442 Need Accept", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["pdf"]["18442_Need_Accept.pdf_id"]["add"] = array("table" => "18442 Need Accept", "field" => "pdf_id", "page" => "add");
	$lookupTableLinks["pdf"]["18442_Need_Accept.pdf_id"]["search"] = array("table" => "18442 Need Accept", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["18442_Need_Accept.pdf_location"]["add"] = array("table" => "18442 Need Accept", "field" => "pdf_location", "page" => "add");
	$lookupTableLinks["jobstatus"]["18442_Need_Accept.jobstatus_id"]["edit"] = array("table" => "18442 Need Accept", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["18442_Need_Accept.jobstatus_id"]["search"] = array("table" => "18442 Need Accept", "field" => "jobstatus_id", "page" => "search");
	$lookupTableLinks["clients"]["18442_Need_Accept.client_id"]["edit"] = array("table" => "18442 Need Accept", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["18442_Need_Accept.project_id"]["edit"] = array("table" => "18442 Need Accept", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["notifyoption"]["18442_Need_Accept.notify_options"]["edit"] = array("table" => "18442 Need Accept", "field" => "notify_options", "page" => "edit");
	$lookupTableLinks["user"]["18442_Need_Accept.reviewer_id"]["add"] = array("table" => "18442 Need Accept", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["pdf"]["Monthly_PDF_Avrage.project_id"]["search"] = array("table" => "Monthly PDF Avrage", "field" => "project_id", "page" => "search");
	$lookupTableLinks["user"]["Daily_Report_Designer_PDF.designer_name"]["search"] = array("table" => "Daily Report Designer PDF", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["pdf"]["Daily_Report_Designer_PDF.pdf_name"]["search"] = array("table" => "Daily Report Designer PDF", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["pdf"]["Monthly_Job_Report__Accepted_.pdf_id"]["search"] = array("table" => "Monthly Job Report (Accepted)", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["team"]["Monthly_Report_Designer_PDF.team"]["search"] = array("table" => "Monthly Report Designer PDF", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["Monthly_Report_Designer_PDF.designer2_id"]["search"] = array("table" => "Monthly Report Designer PDF", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["Monthly_Report_Designer_PDF.project_id"]["search"] = array("table" => "Monthly Report Designer PDF", "field" => "project_id", "page" => "search");
	$lookupTableLinks["pdf"]["Monthly_Job_Report__Notified_.pdf_id"]["search"] = array("table" => "Monthly Job Report (Notified)", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["team"]["14704_Week_Report_Team.team"]["search"] = array("table" => "14704 Week Report Team", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["14704_Week_Report_Team.designer2_id"]["search"] = array("table" => "14704 Week Report Team", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["14704_Week_Report_Team.project_id"]["search"] = array("table" => "14704 Week Report Team", "field" => "project_id", "page" => "search");
	$lookupTableLinks["team"]["14704_Monthly_Designers_Avrage.team"]["search"] = array("table" => "14704 Monthly Designers Avrage", "field" => "team", "page" => "search");
	$lookupTableLinks["user"]["14704_Monthly_Designers_Avrage.designer2_id"]["search"] = array("table" => "14704 Monthly Designers Avrage", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["pdf"]["Designer_files_report.pdf_id"]["search"] = array("table" => "Designer files report", "field" => "pdf_id", "page" => "search");
	$lookupTableLinks["pdf"]["Designer_files_report.pdf_name"]["search"] = array("table" => "Designer files report", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["team"]["Weekly_Report_Designers.team_id"]["search"] = array("table" => "Weekly Report Designers", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Weekly_Report_Designers.designer_name"]["search"] = array("table" => "Weekly Report Designers", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["user"]["Designers_Work_Profile.designer_name"]["search"] = array("table" => "Designers Work Profile", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["Designers_Work_Profile.team_id"]["search"] = array("table" => "Designers Work Profile", "field" => "team_id", "page" => "search");
	$lookupTableLinks["group"]["Designers_Work_Profile.user_group"]["search"] = array("table" => "Designers Work Profile", "field" => "user_group", "page" => "search");
	$lookupTableLinks["team"]["Designers_Performance.team_id"]["search"] = array("table" => "Designers Performance", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Designers_Performance.designer_name"]["search"] = array("table" => "Designers Performance", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["Designers_Performance_Monthly.team_id"]["search"] = array("table" => "Designers Performance Monthly", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Designers_Performance_Monthly.designer_name"]["search"] = array("table" => "Designers Performance Monthly", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["Daily_QC.team_id"]["search"] = array("table" => "Daily QC", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Daily_QC.designer_name"]["search"] = array("table" => "Daily QC", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["generator_rex.team_id"]["search"] = array("table" => "generator_rex", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["generator_rex.designer_name"]["search"] = array("table" => "generator_rex", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["user"]["Display_generator_top_images.designer_name"]["search"] = array("table" => "Display generator_top_images", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["team"]["Display_top_team_performance.team_id"]["search"] = array("table" => "Display_top_team_performance", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Display_top_designer_performance.designer_name"]["search"] = array("table" => "Display_top_designer_performance", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["user"]["Daily_PDF_Avrage.designer_name"]["search"] = array("table" => "Daily PDF Avrage", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["pdf"]["Daily_PDF_Avrage.pdf_name"]["search"] = array("table" => "Daily PDF Avrage", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["pdf"]["Weekly_PDF_Avrage.project_id"]["search"] = array("table" => "Weekly PDF Avrage", "field" => "project_id", "page" => "search");
	$lookupTableLinks["pdf"]["Weekly_PDF_Avrage.pdf_name"]["search"] = array("table" => "Weekly PDF Avrage", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["user"]["Display_top_designer_Files.designer_name"]["search"] = array("table" => "Display_top_designer_Files", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["jobstatus"]["Display_Files_Need_to_Prosess.jobfile_status_id"]["search"] = array("table" => "Display Files Need to Prosess", "field" => "jobfile_status_id", "page" => "search");
	$lookupTableLinks["group"]["attendance_sheet.group_id"]["edit"] = array("table" => "attendance_sheet", "field" => "group_id", "page" => "edit");
	$lookupTableLinks["team"]["attendance_sheet.team"]["edit"] = array("table" => "attendance_sheet", "field" => "team", "page" => "edit");
	$lookupTableLinks["group"]["employee_present.group_id"]["search"] = array("table" => "employee_present", "field" => "group_id", "page" => "search");
	$lookupTableLinks["team"]["employee_present.team"]["search"] = array("table" => "employee_present", "field" => "team", "page" => "search");
	$lookupTableLinks["shifttype"]["employee_present.ShiftTypeId"]["search"] = array("table" => "employee_present", "field" => "ShiftTypeId", "page" => "search");
	$lookupTableLinks["user1"]["UserShift.User_ID"]["edit"] = array("table" => "UserShift", "field" => "User_ID", "page" => "edit");
	$lookupTableLinks["shifttype"]["UserShift.Shift_Type_Id"]["edit"] = array("table" => "UserShift", "field" => "Shift_Type_Id", "page" => "edit");
	$lookupTableLinks["status"]["user1.user_status"]["edit"] = array("table" => "user1", "field" => "user_status", "page" => "edit");
	$lookupTableLinks["department"]["user1.department_id"]["edit"] = array("table" => "user1", "field" => "department_id", "page" => "edit");
	$lookupTableLinks["subdivision"]["user1.subdiv_id"]["edit"] = array("table" => "user1", "field" => "subdiv_id", "page" => "edit");
	$lookupTableLinks["group"]["user1.group_id"]["edit"] = array("table" => "user1", "field" => "group_id", "page" => "edit");
	$lookupTableLinks["team"]["user1.team"]["edit"] = array("table" => "user1", "field" => "team", "page" => "edit");
	$lookupTableLinks["ad_uggroups"]["user1.ad_group_id"]["edit"] = array("table" => "user1", "field" => "ad_group_id", "page" => "edit");
	$lookupTableLinks["designation"]["user1.designation"]["edit"] = array("table" => "user1", "field" => "designation", "page" => "edit");
	$lookupTableLinks["team"]["Daily_Designers_and_QC.team_id"]["search"] = array("table" => "Daily Designers and QC", "field" => "team_id", "page" => "search");
	$lookupTableLinks["user"]["Daily_Designers_and_QC.designer_name"]["search"] = array("table" => "Daily Designers and QC", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["group"]["Daily_Designers_and_QC.user_group"]["search"] = array("table" => "Daily Designers and QC", "field" => "user_group", "page" => "search");
	$lookupTableLinks["work_type"]["Daily_Designers_and_QC.work_type"]["search"] = array("table" => "Daily Designers and QC", "field" => "work_type", "page" => "search");
	$lookupTableLinks["job"]["rejected_job.previous_job_id"]["edit"] = array("table" => "rejected_job", "field" => "previous_job_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["rejected_job.reject_type"]["edit"] = array("table" => "rejected_job", "field" => "reject_type", "page" => "edit");
	$lookupTableLinks["jobstatus"]["rejected_job.jobstatus_id"]["edit"] = array("table" => "rejected_job", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_job.downloader_id"]["add"] = array("table" => "rejected_job", "field" => "downloader_id", "page" => "add");
	$lookupTableLinks["user"]["rejected_job.downloader_id"]["search"] = array("table" => "rejected_job", "field" => "downloader_id", "page" => "search");
	$lookupTableLinks["user"]["rejected_job.distributor_id"]["add"] = array("table" => "rejected_job", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["rejected_job.distributor_id"]["search"] = array("table" => "rejected_job", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["rejected_job.notifer_id"]["add"] = array("table" => "rejected_job", "field" => "notifer_id", "page" => "add");
	$lookupTableLinks["user"]["rejected_job.notifer_id"]["search"] = array("table" => "rejected_job", "field" => "notifer_id", "page" => "search");
	$lookupTableLinks["user"]["rejected_job.reviewer_id"]["search"] = array("table" => "rejected_job", "field" => "reviewer_id", "page" => "search");
	$lookupTableLinks["pdf"]["rejected_job.pdf_id"]["edit"] = array("table" => "rejected_job", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["clients"]["Download_Reject_Job.client_id"]["edit"] = array("table" => "Download Reject Job", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Download_Reject_Job.jobstatus_id"]["edit"] = array("table" => "Download Reject Job", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["jobfile"]["rejected_jobfile2.jobfile_id"]["search"] = array("table" => "rejected_jobfile2", "field" => "jobfile_id", "page" => "search");
	$lookupTableLinks["pdf"]["rejected_jobfile2.project_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["pdf"]["rejected_jobfile2.project_id"]["add"] = array("table" => "rejected_jobfile2", "field" => "project_id", "page" => "add");
	$lookupTableLinks["pdf"]["rejected_jobfile2.project_id"]["search"] = array("table" => "rejected_jobfile2", "field" => "project_id", "page" => "search");
	$lookupTableLinks["work_type"]["rejected_jobfile2.jobfile_type"]["edit"] = array("table" => "rejected_jobfile2", "field" => "jobfile_type", "page" => "edit");
	$lookupTableLinks["jobstatus"]["rejected_jobfile2.jobfile_status_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.downloader_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.distributor_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.qc_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.uploader_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.notifier_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.rejector_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["type_of_errors"]["rejected_jobfile2.reject_reason"]["edit"] = array("table" => "rejected_jobfile2", "field" => "reject_reason", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.designer2_id"]["edit"] = array("table" => "rejected_jobfile2", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["user"]["rejected_jobfile2.designer2_id"]["search"] = array("table" => "rejected_jobfile2", "field" => "designer2_id", "page" => "search");
	$lookupTableLinks["user"]["File_Distribution_Rejected.designer_id"]["edit"] = array("table" => "File Distribution Rejected", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution_Rejected.designer_id"]["add"] = array("table" => "File Distribution Rejected", "field" => "designer_id", "page" => "add");
	$lookupTableLinks["user"]["File_Distribution_Rejected.designer_id"]["search"] = array("table" => "File Distribution Rejected", "field" => "designer_id", "page" => "search");
	$lookupTableLinks["user"]["File_Distribution_Rejected.qc_id"]["edit"] = array("table" => "File Distribution Rejected", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution_Rejected.qc_id"]["add"] = array("table" => "File Distribution Rejected", "field" => "qc_id", "page" => "add");
	$lookupTableLinks["user"]["File_Distribution_Rejected.qc_id"]["search"] = array("table" => "File Distribution Rejected", "field" => "qc_id", "page" => "search");
	$lookupTableLinks["jobstatus"]["File_Distribution_Rejected.jobfile_status_id"]["edit"] = array("table" => "File Distribution Rejected", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["File_Distribution_Rejected.designer2_id"]["edit"] = array("table" => "File Distribution Rejected", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["pdf"]["Designer_Level_2_for_Correction.pdf_id"]["edit"] = array("table" => "Designer Level 2 for Correction", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Level_2_for_Correction.jobstatus_id"]["edit"] = array("table" => "Designer Level 2 for Correction", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2_for_Correction.reviewer_id"]["add"] = array("table" => "Designer Level 2 for Correction", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level_2_for_Correction.notifer_id"]["edit"] = array("table" => "Designer Level 2 for Correction", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2_for_Correction.designer_id"]["edit"] = array("table" => "Designer Level 2 for Correction", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level_2_for_Correction.designer2_id"]["edit"] = array("table" => "Designer Level 2 for Correction", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["clients"]["Designer_Level2_Filesheet_for_Correction.client_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["Designer_Level2_Filesheet_for_Correction.project_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["Designer_Level2_Filesheet_for_Correction.jobfile_status_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.downloader_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.distributor_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.distributor_id"]["add"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.distributor_id"]["search"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.designer_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.qc_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.uploader_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.notifier_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.notifier_id"]["add"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.notifier_id"]["search"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.rejector_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.rejector_id"]["search"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["Designer_Level2_Filesheet_for_Correction.designer2_id"]["edit"] = array("table" => "Designer Level2 Filesheet for Correction", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["pdf"]["QC_Worksheet_for_Correction.pdf_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "pdf_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["QC_Worksheet_for_Correction.jobstatus_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "jobstatus_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet_for_Correction.reviewer_id"]["add"] = array("table" => "QC Worksheet for Correction", "field" => "reviewer_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Worksheet_for_Correction.notifer_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "notifer_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet_for_Correction.designer_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet_for_Correction.designer2_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Worksheet_for_Correction.qc_id"]["edit"] = array("table" => "QC Worksheet for Correction", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["clients"]["QC_Filesheet_for_Correction.client_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "client_id", "page" => "edit");
	$lookupTableLinks["project"]["QC_Filesheet_for_Correction.project_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "project_id", "page" => "edit");
	$lookupTableLinks["jobstatus"]["QC_Filesheet_for_Correction.jobfile_status_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.downloader_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "downloader_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.distributor_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "distributor_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.distributor_id"]["add"] = array("table" => "QC Filesheet for Correction", "field" => "distributor_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.distributor_id"]["search"] = array("table" => "QC Filesheet for Correction", "field" => "distributor_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.designer_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "designer_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.qc_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "qc_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.uploader_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "uploader_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.notifier_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "notifier_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.notifier_id"]["add"] = array("table" => "QC Filesheet for Correction", "field" => "notifier_id", "page" => "add");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.notifier_id"]["search"] = array("table" => "QC Filesheet for Correction", "field" => "notifier_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.rejector_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "rejector_id", "page" => "edit");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.rejector_id"]["search"] = array("table" => "QC Filesheet for Correction", "field" => "rejector_id", "page" => "search");
	$lookupTableLinks["user"]["QC_Filesheet_for_Correction.designer2_id"]["edit"] = array("table" => "QC Filesheet for Correction", "field" => "designer2_id", "page" => "edit");
	$lookupTableLinks["user"]["External_Rejection.qc_id"]["search"] = array("table" => "External Rejection", "field" => "qc_id", "page" => "search");
	$lookupTableLinks["user"]["Internal_Rejection.designer_name"]["search"] = array("table" => "Internal Rejection", "field" => "designer_name", "page" => "search");
	$lookupTableLinks["group"]["Internal_Rejection.group_id"]["search"] = array("table" => "Internal Rejection", "field" => "group_id", "page" => "search");
	$lookupTableLinks["jobstatus"]["Internal_Rejection.work_type"]["search"] = array("table" => "Internal Rejection", "field" => "work_type", "page" => "search");
	$lookupTableLinks["user"]["Daily_Users_Work.user_name"]["search"] = array("table" => "Daily Users Work", "field" => "user_name", "page" => "search");
	$lookupTableLinks["team"]["Daily_Users_Work.team_id"]["search"] = array("table" => "Daily Users Work", "field" => "team_id", "page" => "search");
	$lookupTableLinks["subdivision"]["Daily_Users_Work.subdiv_id"]["search"] = array("table" => "Daily Users Work", "field" => "subdiv_id", "page" => "search");
	$lookupTableLinks["group"]["Daily_Users_Work.user_group"]["search"] = array("table" => "Daily Users Work", "field" => "user_group", "page" => "search");
	$lookupTableLinks["pdf"]["Daily_Users_Work.pdf_name"]["search"] = array("table" => "Daily Users Work", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["work_type"]["Daily_Users_Work.work_type"]["search"] = array("table" => "Daily Users Work", "field" => "work_type", "page" => "search");
	$lookupTableLinks["jobstatus"]["not_for_use.jobfile_status_id"]["edit"] = array("table" => "not for use", "field" => "jobfile_status_id", "page" => "edit");
	$lookupTableLinks["user"]["Daily_Users_Work_Summery.user_name"]["search"] = array("table" => "Daily Users Work Summery", "field" => "user_name", "page" => "search");
	$lookupTableLinks["team"]["Daily_Users_Work_Summery.team_id"]["search"] = array("table" => "Daily Users Work Summery", "field" => "team_id", "page" => "search");
	$lookupTableLinks["group"]["Daily_Users_Work_Summery.user_group"]["search"] = array("table" => "Daily Users Work Summery", "field" => "user_group", "page" => "search");
	$lookupTableLinks["pdf"]["Daily_PDF_Work_Summery.pdf_name"]["search"] = array("table" => "Daily PDF Work Summery", "field" => "pdf_name", "page" => "search");
	$lookupTableLinks["user"]["Daily_Users_Work_Summery_QC.user_name"]["search"] = array("table" => "Daily Users Work Summery QC", "field" => "user_name", "page" => "search");
	$lookupTableLinks["team"]["Daily_Users_Work_Summery_QC.team_id"]["search"] = array("table" => "Daily Users Work Summery QC", "field" => "team_id", "page" => "search");
	$lookupTableLinks["group"]["Daily_Users_Work_Summery_QC.user_group"]["search"] = array("table" => "Daily Users Work Summery QC", "field" => "user_group", "page" => "search");
}

?>