
Runner.pages.PageSettings.addPageEvent("QC Filesheet for Correction",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Start11';if(!pageObj.buttonEventBefore['Start11']){pageObj.buttonEventBefore['Start11']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Downloading Files ...");}}
if(!pageObj.buttonEventAfter['Start11']){pageObj.buttonEventAfter['Start11']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Start11]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Start11"+"_"+Runner.genId();var button_Start11=new Runner.form.Button({id:this.id,btnName:"Start11"});button_Start11.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Filesheet for Correction",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Reject11';if(!pageObj.buttonEventBefore['Reject11']){pageObj.buttonEventBefore['Reject11']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Reject11']){pageObj.buttonEventAfter['Reject11']=function(result,ctrl,pageObj,proxy,pageid,rowData){my_server_share=result["my_server_share"];work_id=result["work_id"];job_id=result["job_id"];file_list=result["file_list"];pdf_id=result["pdf_id"];designer_id=result["designer_id"];designer2_id=result["designer2_id"];qc_id=result["qc_id"];location.href="/"+my_server_share+"/rejected_jobfile_add.php?work_id="+work_id+"&job_id="+job_id+"&file_list="+file_list+"&pdf_id="+pdf_id+"&designer_id="+designer_id+"&designer2_id="+designer2_id+"&qc_id="+qc_id;}}
$('a[id=Reject11]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Reject11"+"_"+Runner.genId();var button_Reject11=new Runner.form.Button({id:this.id,btnName:"Reject11"});button_Reject11.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Filesheet for Correction",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Finish11';if(!pageObj.buttonEventBefore['Finish11']){pageObj.buttonEventBefore['Finish11']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending Files to Server...");}}
if(!pageObj.buttonEventAfter['Finish11']){pageObj.buttonEventAfter['Finish11']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Finish11]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Finish11"+"_"+Runner.genId();var button_Finish11=new Runner.form.Button({id:this.id,btnName:"Finish11"});button_Finish11.init({args:[pageObj,proxy,pageid]});});});