
Runner.pages.PageSettings.addPageEvent("14704 Designer Report",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='QC_Distribute_Files11';if(!pageObj.buttonEventBefore['QC_Distribute_Files11']){pageObj.buttonEventBefore['QC_Distribute_Files11']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";var ctrlDesigner_id=Runner.getControl(pageid,'qc_id');var ctrlFIleId=Runner.getControl(pageid,'file_id[]');params["designer_id"]=ctrlDesigner_id.getValue();params["designer_name"]=ctrlDesigner_id.getDisplayValue();params["work_id"]=work_id;params["job_id"]=job_id;params["file_list"]=new Array();var item_count;for(item_count in thisfile_list){params["file_list"].push(thisfile_list[item_count]);}
ctrl.setMessage("Files are being assigned to: "+params["designer_name"]+" ("+params["designer_id"]+")");}}
if(!pageObj.buttonEventAfter['QC_Distribute_Files11']){pageObj.buttonEventAfter['QC_Distribute_Files11']=function(result,ctrl,pageObj,proxy,pageid,rowData){if(result["distribution_success"]==true)
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION SUCCESSFUL";}
else
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION FAILED";}
ctrl.setMessage(message);}}
$('a[id=QC_Distribute_Files11]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="QC_Distribute_Files11"+"_"+Runner.genId();var button_QC_Distribute_Files11=new Runner.form.Button({id:this.id,btnName:"QC_Distribute_Files11"});button_QC_Distribute_Files11.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("14704 Designer Report",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){total_files=proxy.file_list.length;thisfile_list=proxy.file_list;work_id=proxy.work_id;job_id=proxy.job_id;});