
Runner.pages.PageSettings.addPageEvent("Correction Files",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Start3';if(!pageObj.buttonEventBefore['Start3']){pageObj.buttonEventBefore['Start3']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Downloading Files ...");}}
if(!pageObj.buttonEventAfter['Start3']){pageObj.buttonEventAfter['Start3']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];if(message=="Transfer Failed!"){alert("Transferring Files to Server Failed. Please check.");}
ctrl.setMessage(message);location.reload();}}
$('a[id=Start3]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Start3"+"_"+Runner.genId();var button_Start3=new Runner.form.Button({id:this.id,btnName:"Start3"});button_Start3.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Correction Files",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Finish3';if(!pageObj.buttonEventBefore['Finish3']){pageObj.buttonEventBefore['Finish3']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending Files to Server...");}}
if(!pageObj.buttonEventAfter['Finish3']){pageObj.buttonEventAfter['Finish3']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];if(message=="Transfer Failed!"){alert("Transferring Files to Server Failed. Please check.");}
ctrl.setMessage(message);location.reload();}}
$('a[id=Finish3]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Finish3"+"_"+Runner.genId();var button_Finish3=new Runner.form.Button({id:this.id,btnName:"Finish3"});button_Finish3.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Correction Files",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlRjector_id=Runner.getControl(pageid,'rejector_id');var ctrlRject_date=Runner.getControl(pageid,'reject_date');ctrlRjector_id.setDisabled();ctrlRject_date.setDisabled();total_files=proxy.file_list.length;thisfile_list=proxy.file_list;work_id=proxy.work_id;job_id=proxy.job_id;designer_id=proxy.designer_id;designer2_id=proxy.designer2_id;qc_id=proxy.qc_id;var ctrlJob_Id=Runner.getControl(pageid,'job_id');ctrlJob_Id.setValue(job_id);var ctrlJobfile_Id=Runner.getControl(pageid,'jobfile_id');var ctrlOriginal_Jobfile_Id=Runner.getControl(pageid,'original_jobfile_id');var ctrlOriginal_Designer_Id=Runner.getControl(pageid,'original_designer_id');var ctrlOriginal_Designer2_Id=Runner.getControl(pageid,'original_designer2_id');var ctrlOriginal_Qc_Id=Runner.getControl(pageid,'original_qc_id');var ctrlPdf_Id=Runner.getControl(pageid,'pdf_id');ctrlPdf_Id.setValue(proxy.pdf_id);function func(){ctrlOriginal_Designer_Id.setValue(designer_id);ctrlOriginal_Designer2_Id.setValue(designer2_id);ctrlOriginal_Qc_Id.setValue(qc_id);};ctrlOriginal_Jobfile_Id.setValue(thisfile_list[0]);ctrlJobfile_Id.on('focus',func);ctrlOriginal_Designer_Id.setDisabled();ctrlOriginal_Designer2_Id.setDisabled();ctrlOriginal_Qc_Id.setDisabled();});