
Runner.pages.PageSettings.addPageEvent("custompages",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Empty_The_Designers_Report';if(!pageObj.buttonEventBefore['Empty_The_Designers_Report']){pageObj.buttonEventBefore['Empty_The_Designers_Report']=function(params,ctrl,pageObj,proxy,pageid,rowData){ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Empty_The_Designers_Report']){pageObj.buttonEventAfter['Empty_The_Designers_Report']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"];ctrl.setMessage(message);}}
$('a[id=Empty_The_Designers_Report]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Empty_The_Designers_Report"+"_"+Runner.genId();var button_Empty_The_Designers_Report=new Runner.form.Button({id:this.id,btnName:"Empty_The_Designers_Report"});button_Empty_The_Designers_Report.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("custompages",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_The_Designers_Report';if(!pageObj.buttonEventBefore['Update_The_Designers_Report']){pageObj.buttonEventBefore['Update_The_Designers_Report']=function(params,ctrl,pageObj,proxy,pageid,rowData){ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Update_The_Designers_Report']){pageObj.buttonEventAfter['Update_The_Designers_Report']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"];ctrl.setMessage(message);}}
$('a[id=Update_The_Designers_Report]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Update_The_Designers_Report"+"_"+Runner.genId();var button_Update_The_Designers_Report=new Runner.form.Button({id:this.id,btnName:"Update_The_Designers_Report"});button_Update_The_Designers_Report.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("custompages",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Delete_The_Jobs';if(!pageObj.buttonEventBefore['Delete_The_Jobs']){pageObj.buttonEventBefore['Delete_The_Jobs']=function(params,ctrl,pageObj,proxy,pageid,rowData){ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Delete_The_Jobs']){pageObj.buttonEventAfter['Delete_The_Jobs']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"];ctrl.setMessage(message);}}
$('a[id=Delete_The_Jobs]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Delete_The_Jobs"+"_"+Runner.genId();var button_Delete_The_Jobs=new Runner.form.Button({id:this.id,btnName:"Delete_The_Jobs"});button_Delete_The_Jobs.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("custompages",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Update_The_Designers_Report1';if(!pageObj.buttonEventBefore['Update_The_Designers_Report1']){pageObj.buttonEventBefore['Update_The_Designers_Report1']=function(params,ctrl,pageObj,proxy,pageid,rowData){ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Update_The_Designers_Report1']){pageObj.buttonEventAfter['Update_The_Designers_Report1']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Update_The_Designers_Report1]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Update_The_Designers_Report1"+"_"+Runner.genId();var button_Update_The_Designers_Report1=new Runner.form.Button({id:this.id,btnName:"Update_The_Designers_Report1"});button_Update_The_Designers_Report1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("custompages",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Email_Report';if(!pageObj.buttonEventBefore['Email_Report']){pageObj.buttonEventBefore['Email_Report']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Email_Report']){pageObj.buttonEventAfter['Email_Report']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Email_Report]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Email_Report"+"_"+Runner.genId();var button_Email_Report=new Runner.form.Button({id:this.id,btnName:"Email_Report"});button_Email_Report.init({args:[pageObj,proxy,pageid]});});});