
Runner.pages.PageSettings.addPageEvent("Designer Worksheet",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});Runner.pages.PageSettings.addPageEvent("Designer Worksheet",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});