
Runner.pages.PageSettings.addPageEvent("QC Filesheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Start1';if(!pageObj.buttonEventBefore['Start1']){pageObj.buttonEventBefore['Start1']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Downloading Files ...");}}
if(!pageObj.buttonEventAfter['Start1']){pageObj.buttonEventAfter['Start1']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Start1]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Start1"+"_"+Runner.genId();var button_Start1=new Runner.form.Button({id:this.id,btnName:"Start1"});button_Start1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Filesheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Finish1';if(!pageObj.buttonEventBefore['Finish1']){pageObj.buttonEventBefore['Finish1']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending Files to Server...");}}
if(!pageObj.buttonEventAfter['Finish1']){pageObj.buttonEventAfter['Finish1']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Finish1]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Finish1"+"_"+Runner.genId();var button_Finish1=new Runner.form.Button({id:this.id,btnName:"Finish1"});button_Finish1.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Filesheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Reject1';if(!pageObj.buttonEventBefore['Reject1']){pageObj.buttonEventBefore['Reject1']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Reject1']){pageObj.buttonEventAfter['Reject1']=function(result,ctrl,pageObj,proxy,pageid,rowData){my_server_share=result["my_server_share"];work_id=result["work_id"];job_id=result["job_id"];file_list=result["file_list"];pdf_id=result["pdf_id"];designer_id=result["designer_id"];designer2_id=result["designer2_id"];qc_id=result["qc_id"];location.href="/"+my_server_share+"/rejected_jobfile2_add.php?work_id="+work_id+"&job_id="+job_id+"&file_list="+file_list+"&pdf_id="+pdf_id+"&designer_id="+designer_id+"&designer2_id="+designer2_id+"&qc_id="+qc_id;}}
$('a[id=Reject1]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Reject1"+"_"+Runner.genId();var button_Reject1=new Runner.form.Button({id:this.id,btnName:"Reject1"});button_Reject1.init({args:[pageObj,proxy,pageid]});});});