
Runner.pages.PageSettings.addPageEvent("Designer Level 2 for Correction",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Finish_Job12';if(!pageObj.buttonEventBefore['Finish_Job12']){pageObj.buttonEventBefore['Finish_Job12']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending Files to Server...");}}
if(!pageObj.buttonEventAfter['Finish_Job12']){pageObj.buttonEventAfter['Finish_Job12']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Finish_Job12]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Finish_Job12"+"_"+Runner.genId();var button_Finish_Job12=new Runner.form.Button({id:this.id,btnName:"Finish_Job12"});button_Finish_Job12.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Designer Level 2 for Correction",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Start_Job33';if(!pageObj.buttonEventBefore['Start_Job33']){pageObj.buttonEventBefore['Start_Job33']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Downloading Files ...");}}
if(!pageObj.buttonEventAfter['Start_Job33']){pageObj.buttonEventAfter['Start_Job33']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Start_Job33]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Start_Job33"+"_"+Runner.genId();var button_Start_Job33=new Runner.form.Button({id:this.id,btnName:"Start_Job33"});button_Start_Job33.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Designer Level 2 for Correction",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});Runner.pages.PageSettings.addPageEvent("Designer Level 2 for Correction",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});