
Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Distribute12';if(!pageObj.buttonEventBefore['Distribute12']){pageObj.buttonEventBefore['Distribute12']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Feature Inactive");}}
if(!pageObj.buttonEventAfter['Distribute12']){pageObj.buttonEventAfter['Distribute12']=function(result,ctrl,pageObj,proxy,pageid,rowData){work_id=result["work_id"];job_id=result["job_id"];file_list=result["file_list"];server_url=result["server_url"];my_server_share=result["my_server_share"];location.href=server_url+"file_distribution_add.php?work_id="+work_id+"&job_id="+job_id+"&file_list="+file_list+"&designer_level=2";}}
$('a[id=Distribute12]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Distribute12"+"_"+Runner.genId();var button_Distribute12=new Runner.form.Button({id:this.id,btnName:"Distribute12"});button_Distribute12.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Distribute_to_QC2';if(!pageObj.buttonEventBefore['Distribute_to_QC2']){pageObj.buttonEventBefore['Distribute_to_QC2']=function(params,ctrl,pageObj,proxy,pageid,rowData){}}
if(!pageObj.buttonEventAfter['Distribute_to_QC2']){pageObj.buttonEventAfter['Distribute_to_QC2']=function(result,ctrl,pageObj,proxy,pageid,rowData){my_server_share=result["my_server_share"];work_id=result["work_id"];job_id=result["job_id"];file_list=result["file_list"];location.href="/"+my_server_share+"/file_distribution_edit.php?work_id="+work_id+"&job_id="+job_id+"&file_list="+file_list;}}
$('a[id=Distribute_to_QC2]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Distribute_to_QC2"+"_"+Runner.genId();var button_Distribute_to_QC2=new Runner.form.Button({id:this.id,btnName:"Distribute_to_QC2"});button_Distribute_to_QC2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='QC_Distribute_Files2';if(!pageObj.buttonEventBefore['QC_Distribute_Files2']){pageObj.buttonEventBefore['QC_Distribute_Files2']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";var ctrlDesigner_id=Runner.getControl(pageid,'qc_id');var ctrlFIleId=Runner.getControl(pageid,'file_id[]');params["designer_id"]=ctrlDesigner_id.getValue();params["designer_name"]=ctrlDesigner_id.getDisplayValue();params["work_id"]=work_id;params["job_id"]=job_id;params["file_list"]=new Array();var item_count;for(item_count in thisfile_list){params["file_list"].push(thisfile_list[item_count]);}
ctrl.setMessage("Files are being assigned to: "+params["designer_name"]+" ("+params["designer_id"]+")");}}
if(!pageObj.buttonEventAfter['QC_Distribute_Files2']){pageObj.buttonEventAfter['QC_Distribute_Files2']=function(result,ctrl,pageObj,proxy,pageid,rowData){if(result["distribution_success"]==true)
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION SUCCESSFUL";}
else
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION FAILED";}
ctrl.setMessage(message);}}
$('a[id=QC_Distribute_Files2]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="QC_Distribute_Files2"+"_"+Runner.genId();var button_QC_Distribute_Files2=new Runner.form.Button({id:this.id,btnName:"QC_Distribute_Files2"});button_QC_Distribute_Files2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Distribute_Files2';if(!pageObj.buttonEventBefore['Distribute_Files2']){pageObj.buttonEventBefore['Distribute_Files2']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";var ctrlDesigner_id=Runner.getControl(pageid,'designer_id');var ctrlFIleId=Runner.getControl(pageid,'file_id[]');params["designer_id"]=ctrlDesigner_id.getValue();params["designer_name"]=ctrlDesigner_id.getDisplayValue();params["work_id"]=work_id;params["job_id"]=job_id;params["file_list"]=new Array();params["designer_level"]=designer_level;var item_count;for(item_count in thisfile_list){params["file_list"].push(thisfile_list[item_count]);}
ctrl.setMessage("Files are being assigned to: "+params["designer_name"]+" ("+params["designer_id"]+")");}}
if(!pageObj.buttonEventAfter['Distribute_Files2']){pageObj.buttonEventAfter['Distribute_Files2']=function(result,ctrl,pageObj,proxy,pageid,rowData){my_server_share=result["my_server_share"];if(result["distribution_success"]==true)
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION SUCCESSFUL";}
else
{var message="Total Files: "+result["total_files"]+" | Work ID: "+result["work_id"]+" | Job ID: "+result["job_id"]+" | Distributed to: "+result["designer_name"]+" ("+result["designer_id"]+")<br> DISTRIBUTION FAILED";}
ctrl.setMessage(message);}}
$('a[id=Distribute_Files2]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Distribute_Files2"+"_"+Runner.genId();var button_Distribute_Files2=new Runner.form.Button({id:this.id,btnName:"Distribute_Files2"});button_Distribute_Files2.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){total_files=proxy.file_list.length;thisfile_list=proxy.file_list;work_id=proxy.work_id;job_id=proxy.job_id;designer_level=proxy.designer_level;});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var submitUrl="imprimir_lote_pdf.php";if(typeof id=="undefined")
{id=this.id;}
pageObj=this;$("#imprimir_seleccion"+this.id).unbind("click").bind("click",function(e){var selBoxes=$('input[@type=checkbox][@checked][@id^=check'+id+'_]');if(selBoxes.length==0||!confirm('Are You Sure?')){return false;}
var form=new Runner.form.BasicForm({standardSubmit:true,submitUrl:submitUrl,method:'POST',id:pageObj.id,baseParams:{"a":'lote'},addElems:cloneElements(selBoxes)});return openwin(form);form.destructor();});var prevWin=null;function openwin(oForm)
{if(prevWin&&!prevWin.closed)
prevWin.close();var form=new Runner.form.BasicForm({standardSubmit:true,submitUrl:submitUrl,method:'POST',id:pageObj.id,baseParams:{"a":'lote'},addElems:cloneElements(selBoxes)});prevWin=window.open('','prevWin','left=200,top=200,width=750,height=620,status=0');oForm.target='prevWin';oForm.action='imprimir_lote_pdf.php';oForm.submit();if(prevWin&&!prevWin.closed)
prevWin.focus();return true;}
$(document).ready(function(){$("td").filter(':has(:checkbox:checked)').addClass('selected').end().click(function(event){if(event.target.type!=='checkbox'){$(':checkbox',this).trigger('click');}}).find(':checkbox').click(function(event){$(this).parents('tr:first').toggleClass('selected');});});;});Runner.pages.PageSettings.addPageEvent("Multi Reject",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){total_files=proxy.file_list.length;thisfile_list=proxy.file_list;work_id=proxy.work_id;job_id=proxy.job_id;});