
Runner.pages.PageSettings.addPageEvent("Delected Jobs",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Action1_label16';if(!pageObj.buttonEventBefore['Action1_label16']){pageObj.buttonEventBefore['Action1_label16']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Action1_label16']){pageObj.buttonEventAfter['Action1_label16']=function(result,ctrl,pageObj,proxy,pageid,rowData){work_id=result.record["work_id"];job_id=result.record["job_id"];jobstatus_id=result.record["jobstatus_id"];if(jobstatus_id==12)
{location.href="/visionwebapp_alex/download_job_list.php?work_id="+work_id+"&job_id="+job_id;}
else if(jobstatus_id==9)
location.href="/visionwebapp_alex/delete_job_list.php?work_id="+work_id+"&job_id="+job_id;else if(jobstatus_id==1)
location.href="/visionwebapp_alex/Pending_Jobs_list.php";else if(jobstatus_id==2||jobstatus_id==3||jobstatus_id==20)
{var a=document.createElement('a');a.href="/visionwebapp_alex/download_job_list.php?work_id="+work_id+"&job_id="+job_id;a.target='_blank';document.body.appendChild(a);a.click();location.href="/visionwebapp_alex/Pending_Jobs_list.php";}}}
$('a[id=Action1_label16]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Action1_label16"+"_"+Runner.genId();var button_Action1_label16=new Runner.form.Button({id:this.id,btnName:"Action1_label16"});button_Action1_label16.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("Delected Jobs",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){$(":checkbox").change(function(){$(this).closest("tr").find("td").toggleClass("checkedHighlight",this.checked);});$("#chooseAll_1").change(function(){$('#chooseAll_1').closest("table").find("tr").find("td").toggleClass("checkedHighlight",this.checked);});$(document).ready(function(){$("tr[id^=gridRow]").filter(':has(:checkbox:checked)').addClass('selected').end().click(function(event){if(event.target.type!=='checkbox'){$(':checkbox',this).trigger('click');}}).find(':checkbox').click(function(event){$(this).parents('tr:first').toggleClass('selected');});});$(":checkbox").change(function(){$(this).closest("tr").find("td").toggleClass("checkedHighlight",this.checked);});$("#chooseAll_1").change(function(){$('#chooseAll_1').closest("table").find("tr").find("td").toggleClass("checkedHighlight",this.checked);});});