
Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Start_Job';if(!pageObj.buttonEventBefore['Start_Job']){pageObj.buttonEventBefore['Start_Job']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Downloading Files ...");}}
if(!pageObj.buttonEventAfter['Start_Job']){pageObj.buttonEventAfter['Start_Job']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Start_Job]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Start_Job"+"_"+Runner.genId();var button_Start_Job=new Runner.form.Button({id:this.id,btnName:"Start_Job"});button_Start_Job.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Finish_Job';if(!pageObj.buttonEventBefore['Finish_Job']){pageObj.buttonEventBefore['Finish_Job']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending Files to Server...");}}
if(!pageObj.buttonEventAfter['Finish_Job']){pageObj.buttonEventAfter['Finish_Job']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["action_response"];ctrl.setMessage(message);location.reload();}}
$('a[id=Finish_Job]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Finish_Job"+"_"+Runner.genId();var button_Finish_Job=new Runner.form.Button({id:this.id,btnName:"Finish_Job"});button_Finish_Job.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Reject_Job';if(!pageObj.buttonEventBefore['Reject_Job']){pageObj.buttonEventBefore['Reject_Job']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Hello";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Reject_Job']){pageObj.buttonEventAfter['Reject_Job']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Reject_Job]').each(function(){if($(this).closest('tr.gridRowAdd').length){return;}
this.id="Reject_Job"+"_"+Runner.genId();var button_Reject_Job=new Runner.form.Button({id:this.id,btnName:"Reject_Job"});button_Reject_Job.init({args:[pageObj,proxy,pageid]});});});Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){var ctrlComplexity1=Runner.getControl(pageid,'complexity1');var ctrlComplexity2=Runner.getControl(pageid,'complexity2');var ctrlComplexity3=Runner.getControl(pageid,'complexity3');var ctrlComplexity4=Runner.getControl(pageid,'complexity4');var ctrlComplexity5=Runner.getControl(pageid,'complexity5');var ctrlCustomComplexity=Runner.getControl(pageid,'custom_complexity');var ctrlTotal=Runner.getControl(pageid,'total_images');var ctrlDelivery_date=Runner.getControl(pageid,'delivery_date');var ctrlDelivery_duration=Runner.getControl(pageid,'delivery_duration');var ctrlReviewer_id=Runner.getControl(pageid,'reviewer_id');ctrlReviewer_id.setDisabled();function func(){ctrlTotal.setValue(Number(ctrlComplexity1.getValue())
+Number(ctrlComplexity2.getValue())
+Number(ctrlComplexity3.getValue())
+Number(ctrlComplexity4.getValue())
+Number(ctrlComplexity5.getValue())
+Number(ctrlCustomComplexity.getValue()));};ctrlComplexity1.on('keyup',func);ctrlComplexity2.on('keyup',func);ctrlComplexity3.on('keyup',func);ctrlComplexity4.on('keyup',func);ctrlComplexity5.on('keyup',func);ctrlCustomComplexity.on('keyup',func);Date.prototype.addHours=function(h){this.setHours(this.getHours()+h);return this;}
function delivery_duration_add(){var dateString="Today's date is: ";var newDate=new Date();var add_time=ctrlDelivery_duration.getValue()*60*60*1000;newDate.setMilliseconds(add_time);dateString+=newDate.getDate()+"/";dateString+=(newDate.getMonth()+1)+"/";dateString+=newDate.getFullYear();dateString+=" "+newDate.getHours()+":"+newDate.getMinutes()+":"+newDate.getSeconds();ctrlDelivery_date.setValue(dateString);};ctrlDelivery_duration.on('change',delivery_duration_add);});Runner.pages.PageSettings.addPageEvent("QC Worksheet",Runner.pages.constants.PAGE_LIST,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject){function popmyprogress(url,title,w,h){var left=(screen.width/2)-(w/2);var top=(screen.height/2)-(h/2);return window.open(url,title,'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);};});